/*
 * HandsUpAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/26/2016
 */
package cn.responder.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CourseTime 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5501038240153945772L;
    private String classDay;
    private String classRoom;
    private String classTime;
    private String classWeek;
    /** GETTER
     * 星期几
     */
    @JsonGetter("classDay")
    public String getClassDay ( ) { 
        return this.classDay;
    }
    
    /** SETTER
     * 星期几
     */
    @JsonSetter("classDay")
    public void setClassDay (String value) { 
        this.classDay = value;
        notifyObservers(this.classDay);
    }
 
    /** GETTER
     * 上课教室
     */
    @JsonGetter("classRoom")
    public String getClassRoom ( ) { 
        return this.classRoom;
    }
    
    /** SETTER
     * 上课教室
     */
    @JsonSetter("classRoom")
    public void setClassRoom (String value) { 
        this.classRoom = value;
        notifyObservers(this.classRoom);
    }
 
    /** GETTER
     * 一天中课节
     */
    @JsonGetter("classTime")
    public String getClassTime ( ) { 
        return this.classTime;
    }
    
    /** SETTER
     * 一天中课节
     */
    @JsonSetter("classTime")
    public void setClassTime (String value) { 
        this.classTime = value;
        notifyObservers(this.classTime);
    }
 
    /** GETTER
     * 哪些周
     */
    @JsonGetter("classWeek")
    public String getClassWeek ( ) { 
        return this.classWeek;
    }
    
    /** SETTER
     * 哪些周
     */
    @JsonSetter("classWeek")
    public void setClassWeek (String value) { 
        this.classWeek = value;
        notifyObservers(this.classWeek);
    }
 
}
 