/*
 * HandsUpAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 05/06/2016
 */
package cn.responder;

import cn.responder.controllers.*;
import cn.responder.http.client.HttpClient;

public class HandsUpAPIClient {
    /**
     * Singleton access to LoginorEnroll controller
     * @return	Returns the LoginorEnrollController instance 
     */
    public LoginorEnrollController getLoginorEnroll() {
        return LoginorEnrollController.getInstance();
    }

    /**
     * Singleton access to StudentOpreation controller
     * @return	Returns the StudentOpreationController instance 
     */
    public StudentOpreationController getStudentOpreation() {
        return StudentOpreationController.getInstance();
    }

    /**
     * Singleton access to TeacherOperation controller
     * @return	Returns the TeacherOperationController instance 
     */
    public TeacherOperationController getTeacherOperation() {
        return TeacherOperationController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public HandsUpAPIClient() { }
}