/*
 * HandsUpAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 05/06/2016
 */
package cn.responder.controllers;

import cn.responder.APIException;
import cn.responder.http.client.HttpClient;
import cn.responder.http.client.HttpContext;
import cn.responder.http.client.VolleyClient;
import cn.responder.http.response.HttpResponse;

public abstract class BaseController {
    /**
     * Private variable to keep shared reference of client instance
     */
    private static HttpClient clientInstance = null;
    private static Object syncObject = new Object();
    
    /**
     * Shared instance of the Http client
     * @return The shared instance of the http client 
     */
    public static HttpClient getClientInstance() {
        synchronized (syncObject) {
            if (null == clientInstance) {
                clientInstance = VolleyClient.getSharedInstance();
            }
        }
        return clientInstance;
    }

    /**
     * Shared instance of the Http client
     * @param	client	The shared instance of the http client 
     */
    public static void setClientInstance(HttpClient client) {
        synchronized (syncObject) {
            if (null != client) {
                clientInstance = client;
            }
        }
    }

    /**
     * Validates the response against HTTP errors defined at the API level
     * @param	_response	The response recieved
     * @param	_context	Context of the request and the recieved response 
     */
    protected void validateResponse(HttpResponse response, HttpContext context) 
            throws APIException {
        //get response status code to validate
        int responseCode = response.getStatusCode();
        if (responseCode == 500)
            throw new APIException("服务器错误", context);

        else if (responseCode == 502)
            throw new APIException("密码错误", context);

        else if (responseCode == 501)
            throw new APIException("用户不存在", context);

        else if (responseCode == 503)
            throw new APIException("该用户已存在", context);

        else if (responseCode == 504)
            throw new APIException("该课程已存在", context);

        else if ((responseCode < 200) || (responseCode > 206)) //[200,206] = HTTP OK
            throw new APIException("HTTP Response Not OK", context);
    }
}
