/*
 * HandsUpAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 05/06/2016
 */
package cn.responder.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;

import cn.responder.http.client.HttpClient;
import cn.responder.http.client.HttpContext;
import cn.responder.http.request.HttpRequest;
import cn.responder.http.response.HttpResponse;
import cn.responder.http.response.HttpStringResponse;
import cn.responder.http.client.APICallBack;
import cn.responder.*;

public class LoginorEnrollController extends BaseController {    
    //private static variables for the singleton pattern
    private static Object syncObject = new Object();
    private static LoginorEnrollController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the LoginorEnrollController class 
     */
    public static LoginorEnrollController getInstance() {
        synchronized (syncObject) {
            if (null == instance) {
                instance = new LoginorEnrollController();
            }
        }
        return instance;
    }

    /**
     * TODO: type endpoint description here
     * @param    userName    Required parameter: TODO: type description here
     * @param    userNumber    Required parameter: TODO: type description here
     * @param    userPassword    Required parameter: TODO: type description here
     * @param    userRole    Required parameter: TODO: type description here
     * @return	Returns the void response from the API call 
     */
    public void getEnrollAsync(
                final String userName,
                final String userNumber,
                final String userPassword,
                final String userRole,
                final APICallBack<String> callBack
    ) {
        //the base uri for api requests
        String baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder queryBuilder = new StringBuilder(baseUri);
        queryBuilder.append("/register");

        //process query parameters
        APIHelper.appendUrlWithQueryParameters(queryBuilder, new HashMap<String, Object>() {
            private static final long serialVersionUID = 4887519633426501637L;
            {
                    put( "userName", userName );
                    put( "userNumber", userNumber );
                    put( "userPassword", userPassword );
                    put( "userRole", userRole );
            }});
        //validate and preprocess url
        String queryUrl = APIHelper.cleanUrl(queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> headers = new HashMap<String, String>() {
            private static final long serialVersionUID = 5102263157582674797L;
            {
                    put( "user-agent", "APIMATIC 2.0" );
            }
        };

        //prepare and invoke the API call request to fetch the response
        final HttpRequest request = getClientInstance().get(queryUrl, headers, null);

        //invoke request and get response
        Runnable responseTask = new Runnable() {
            public void run() {
                //make the API call
                getClientInstance().executeAsStringAsync(request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext context, HttpResponse response) {
                        try {
                            //Error handling using HTTP status codes
                            int responseCode = response.getStatusCode();
                            if (responseCode == 503)
                                throw new APIException("该用户已存在", context);

                            else if ((responseCode < 200) || (responseCode > 206)) //[200,206] = HTTP OK
                                throw new APIException("HTTP Response Not OK", context);

                            //handle errors defined at the API level
                            validateResponse(response, context);

                            //extract result from the http response
                            String result = ((HttpStringResponse)response).getBody();
                            //let the caller know of the success
                            callBack.onSuccess(context, result);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(context, error);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(context, exception);
                        }
                    }
                    public void onFailure(HttpContext context, Throwable error) {
                        //let the caller know of the failure
                        callBack.onFailure(context, error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(responseTask);
    }
        
    /**
     * TODO: type endpoint description here
     * @param    userNumber    Required parameter: TODO: type description here
     * @param    userPassword    Required parameter: TODO: type description here
     * @param    userRole    Required parameter: TODO: type description here
     * @return	Returns the void response from the API call 
     */
    public void getLoginAsync(
                final String userNumber,
                final String userPassword,
                final String userRole,
                final APICallBack<String> callBack
    ) {
        //the base uri for api requests
        String baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder queryBuilder = new StringBuilder(baseUri);
        queryBuilder.append("/login");

        //process query parameters
        APIHelper.appendUrlWithQueryParameters(queryBuilder, new HashMap<String, Object>() {
            private static final long serialVersionUID = 4930676943618792800L;
            {
                    put( "userNumber", userNumber );
                    put( "userPassword", userPassword );
                    put( "userRole", userRole );
            }});
        //validate and preprocess url
        String queryUrl = APIHelper.cleanUrl(queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> headers = new HashMap<String, String>() {
            private static final long serialVersionUID = 5282998112095097921L;
            {
                    put( "user-agent", "APIMATIC 2.0" );
            }
        };

        //prepare and invoke the API call request to fetch the response
        final HttpRequest request = getClientInstance().get(queryUrl, headers, null);

        //invoke request and get response
        Runnable responseTask = new Runnable() {
            public void run() {
                //make the API call
                getClientInstance().executeAsStringAsync(request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext context, HttpResponse response) {
                        try {
                            //Error handling using HTTP status codes
                            int responseCode = response.getStatusCode();
                            if (responseCode == 501)
                                throw new APIException("用户不存在", context);

                            else if (responseCode == 502)
                                throw new APIException("密码错误", context);

                            else if ((responseCode < 200) || (responseCode > 206)) //[200,206] = HTTP OK
                                throw new APIException("HTTP Response Not OK", context);

                            //handle errors defined at the API level
                            validateResponse(response, context);

                            //extract result from the http response
                            String result = ((HttpStringResponse)response).getBody();
                            //let the caller know of the success
                            callBack.onSuccess(context, result);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(context, error);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(context, exception);
                        }
                    }
                    public void onFailure(HttpContext context, Throwable error) {
                        //let the caller know of the failure
                        callBack.onFailure(context, error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(responseTask);
    }
        
}